### ISSUE TITLE
Are the scripts used to parse the PDF files available?

### ISSUE THREAD

**Issue by lematt1991** [cdcepi/zika#163]
I'm curious about how the CSV files were generated and was hoping to look at the scripts that were used for parsing the PDF documents found in the repository.  Are these available somewhere?

**Comment by dmrodz** [comment]
For most, I convert the PDFs to excel or word and go from there. No specific script, since the data is just a quick copy-paste away. This is mostly because most PDF files contain copies of pictures and not "true tables."
I did write a small API in R to gather US data under [CDC Report](https://github.com/cdcepi/zika/tree/master/United_States/CDC_Report/code), depending on whether I scrape those from the web archives or directly from the CDC site.

**Comment by lematt1991** [comment]
Are you open to accepting pull requests that automate this process?  It might be easier to keep things up to date this way.

**Comment by dmrodz** [comment]
Feel free!

**Comment by dmrodz** [comment]
Please, add them [here.](https://github.com/cdcepi/zika/tree/master/code/contributions)
Thanks!
