### ISSUE TITLE
Places metadata for Colombia

### ISSUE THREAD

**Issue by chendaniely** [cdcepi/zika#17]
There needs to be a `CO_Places.csv` file that needs the following columns
- location
- location_type
- country
- state_province
- district_county_municipality
- city
- alt_name1
- alt_name2

While cleaning the Colombia data, the `department` and `municipality` columns can be used to create the `CO_Places.csv` file

After A bit of cleaning I have this:

![selection_011](https://cloud.githubusercontent.com/assets/5782147/13450285/9b4542a0-e001-11e5-9493-b4bb74f7ad63.png)

The first set of questions are:
1. How do I address the `Municipio Desconocido` which means "Unknown municipality". I believe they are unknown counts for a particular municipality, but I could be wrong
2. Does `department` map to `state_province` and `municipality` maps to `district_county_municipality`?

Next, there are 94 observations that look like the following:
![selection_012](https://cloud.githubusercontent.com/assets/5782147/13450347/4d4fea54-e002-11e5-80ce-423e73b540cc.png)
1. Is `BOGOTA` a state and municipality?
2. would the `[country]-[state/province]-[county/municipality/city]` format then be: `CO-Bogota-Bogota-Usaquen-Los Cedros`?
   - would the hyphens between cities be confusing?
   - One option is to replace the hyphens in city names into underscores, or change the `[country]-[state/province]-[county/municipality/city]` to be `[country]_[state/province]_[county/municipality/city]`

**Comment by cdcepi** [comment]
First set:
1. Yes, I think all of the "Municipio Desconocido" have a known department, so you can create a "place" called Unknown Municipio in each department
2. Yes, department maps to state and municipio to municipality

Second set:
1. Treat Bogota as a department since that convention is used in the report. D.C. is Distrito Capital. You can remove "Bogota" (and the other department names) from the Municipio names
2. I prefer option 2: replace the hyphens in city names into underscores. That will be consistent with the other Places files so that all can be parsed by hyphen

(3.) The alt_name columns are there in case there is some other useful version you would like to include, e.g. the hyphenated version
